name: Extract Location URL

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "7,37 * * * *"

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract Location
        run: |
          curl -sI \
            -A "OTT Navigator/1.7.2.2 (Linux;Android 11; en; 1nsjitl)" \
            "https://vortexsu.azmodz.in/vortextv/serve/jionormal/678.mpd" \
            | grep -i "^location:" \
            | sed 's/^[Ll]ocation:[[:space:]]*//' \
            | tr -d '\r' > location.txt

      - name: Commit if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions.com"

          git add location.txt

          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Update location URL"
            git push
          fi
